---
- name: Install Prometheus Node Exporter
  hosts: all
  become: true
  remote_user: vagrant
  
  tasks:
    - name: Download Node Exporter archive
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-0.18.1.tar.gz"
    
    - name: Extract Node Exporter archive
      unarchive:
        src: "/tmp/node_exporter-0.18.1.tar.gz"
        dest: "/opt"
        remote_src: true
    
    - name: Rename Node Exporter directory
      command: mv /opt/node_exporter-0.18.1.linux-amd64 /opt/node_exporter

    - name: Create Ubuntu user
      user:
        name: node_exporter
        state: present
        createhome: yes
        shell: /bin/bash
    
    - name: Create Node Exporter systemd service
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify:
        - Reload systemd
    
    - name: Start Node Exporter service
      service:
        name: node_exporter
        state: started
        enabled: true
  
  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
        state: reloaded
